baseURL = 'https://linushuan.github.io/blog/ani/'
languageCode = 'zh-TW'
# defaultContentLanguage = 'zh-TW'
title = "Wonderhoi's Realm"
theme = 'reimu'
layoutDir = 'layouts-ani'
publishDir = 'public/ani'
mainSections = ["posts"]
hasCJKLanguage = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  guessSyntax = true

[markup.goldmark.extensions]
  strikethrough = false

  [markup.goldmark.extensions.extras.delete]
    enable = true
  [markup.goldmark.extensions.extras.subscript]
    enable = true
  [markup.goldmark.extensions.extras.superscript]
    enable = true
  [markup.goldmark.extensions.extras.insert]
    enable = true
  [markup.goldmark.extensions.extras.mark]
    enable = true

  [markup.goldmark.extensions.cjk]
    enable = true
    eastAsianLineBreaks = true
    eastAsianLineBreaksStyle = "css3draft"

  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [["\\[", "\\]"], ["$$", "$$"]]
      inline = [["\\(", "\\)"], ["$", "$"]]
