baseURL = 'https://linushuan.github.io/blog/ani/'
languageCode = 'zh-TW'
# defaultContentLanguage = 'zh-TW'
title = "Wonderhoi's Realm"
theme = 'reimu'
layoutDir = 'layouts-ani'
publishDir = 'public/ani'
mainSections = ["posts"]
hasCJKLanguage = true

[markup.highlight]
  noClasses = false
  guessSyntax = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["\\[", "\\]"], ["$$", "$$"]]
    inline = [["\\(", "\\)"], ["$", "$"]]
