baseURL = 'https://linushuan.github.io/blog/ani/'
languageCode = 'zh-tw'
title = "Wonderhoi's Realm"
theme = 'reimu'
publishDir = 'public/ani'

[[menu.main]]
    name = "ホーム"
    url = "/blog/ani/"
    weight = 1
[[menu.main]]
    name = "投稿一覧"
    url = "/blog/ani/posts/"
    weight = 2
[[menu.main]]
    name = "タグ"
    url = "/blog/ani/tags/"
    weight = 3
[[menu.main]]
    name = "自己紹介"
    url = "/blog/ani/about/"
    weight = 4
[[menu.main]]
    name = "様式"
    url = "/blog/sim/"
    weight = 5

[params]
    math = true
    author = "Linuk"
